### ISSUE TITLE
npm start fails with error

### ISSUE THREAD

**Issue by dtmunir** [peteryunkim/1DocWayExercise#1]
```
➜  1DocWayExercise git:(master) npm start

> patientportal@0.1.0 start /Users/dtmunir/Dev/1DocWay/interviews/peter-kim/1DocWayExercise
> react-scripts start

/Users/dtmunir/Dev/1DocWay/interviews/peter-kim/1DocWayExercise/node_modules/react-scripts/scripts/start.js:33
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/5.4.1_1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! patientportal@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the patientportal@0.1.0 start script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the patientportal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs patientportal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls patientportal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dtmunir/Dev/1DocWay/interviews/peter-kim/1DocWayExercise/npm-debug.log
➜  1DocWayExercise git:(master) node -v
v5.4.1
➜  1DocWayExercise git:(master) npm -v
3.5.3
```

**Comment by dtmunir** [comment]
nvm. This was resolved by updating node and npm
